/* JAS Meeting module — isolated renderer. Sector Wise first, Facility Wise second. */
(function(){
'use strict';
const GID='1018164338'; const SID='1XAGjeCrLSVzTIraRSGkkjejXlrJEn-G2GxUEnN6ZCI0';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=v=>Number(String(v??'').replace(/,/g,'').replace('%','').trim())||0;
const clean=v=>String(v??'').trim(); const pc=v=>n(v)>=100?'jas-pct-green':'jas-pct-red';
function css(){if(document.getElementById('jas-fixed-css'))return;const s=document.createElement('style');s.id='jas-fixed-css';s.textContent=`#jasMeetingModule{display:block!important;width:100%}.jas-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:0 0 14px}.jas-card{padding:12px;border-radius:10px;text-align:center;border:1px solid #ddd;background:#fff}.jas-card b{display:block;font-size:20px}.jas-card span{font-size:11px;font-weight:700}.jas-page{background:#fff;padding:10px;margin:0 0 14px;overflow:auto;border-radius:12px}.jas-table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:11px}.jas-table th,.jas-table td{border:1px solid #bbb;padding:6px 4px;text-align:center;vertical-align:middle;word-break:break-word}.jas-title{font-size:15px;font-weight:800}.jas-table th{font-weight:800}.jas-name{text-align:left}.jas-total{font-weight:800}.jas-pct-green{color:#008000!important;font-weight:800}.jas-pct-red{color:#d00!important;font-weight:800}@media(max-width:700px){.jas-summary{grid-template-columns:repeat(2,1fr)}.jas-table{font-size:9px}}`;document.head.appendChild(s)}
function rows(dt){const a=[];for(let r=0;r<dt.getNumberOfRows();r++){let v=[];for(let c=0;c<6;c++)v.push(clean(dt.getFormattedValue(r,c)));a.push(v)}return a}
function parse(a){let sec=false,fac=false,sector=[],facility=[],sh=null,fh=null,title='Jan Arogya Samiti Meeting FY 2026-27 Till July 2026';for(const v of a){const text=v.join(' ').toLowerCase();if(text.includes('jan arogya samiti')){if(!sec&&!fac)title=v.find(Boolean)||title;continue}if(text.includes('no of aam facility')){sec=true;fac=false;sh=v;continue}if(text.includes('name of facility')||text==='sn nin name of facility target till july 26 achievment %'){sec=false;fac=true;fh=v;continue}if(text.includes('total'))continue;if(!/^\d+$/.test(v[0]))continue;if(sec&&v[1]&&/^\d+$/.test(v[2]))sector.push(v);else if(fac&&v[1]&&v[2])facility.push(v)}return{sector,facility,sh,fh,title}}
function th(h,i,d){return esc(clean(h?.[i])||d)}
function sectorTable(a,H,title){let h='<table class="jas-table"><thead><tr><th colspan="6" class="jas-title">'+esc(title)+'</th></tr><tr>';['SN','Sector','No of AAM Facility','Target till May 26','Achievment','%'].forEach((d,i)=>h+='<th>'+th(H,i,d)+'</th>');h+='</tr></thead><tbody>';let f=0,t=0,x=0;a.forEach(v=>{let F=n(v[2]),T=n(v[3]),X=n(v[4]),P=n(v[5]);f+=F;t+=T;x+=X;h+='<tr><td>'+esc(v[0])+'</td><td class="jas-name">'+esc(v[1])+'</td><td>'+F+'</td><td>'+T+'</td><td>'+X+'</td><td class="'+pc(P)+'">'+P+'%</td></tr>'});h+='<tr class="jas-total"><td colspan="2">Total</td><td>'+f+'</td><td>'+t+'</td><td>'+x+'</td><td></td></tr></tbody></table>';return{h,f,t,x}}
function facilityTable(a,H,title){let h='<table class="jas-table"><thead><tr><th colspan="6" class="jas-title">'+esc(title)+'</th></tr><tr>';['SN','NIN','Name of Facility','Target till July 26','Achievment','%'].forEach((d,i)=>h+='<th>'+th(H,i,d)+'</th>');h+='</tr></thead><tbody>';let t=0,x=0;a.forEach(v=>{let T=n(v[3]),X=n(v[4]),P=n(v[5]);t+=T;x+=X;h+='<tr><td>'+esc(v[0])+'</td><td>'+esc(v[1])+'</td><td class="jas-name">'+esc(v[2])+'</td><td>'+T+'</td><td>'+X+'</td><td class="'+pc(P)+'">'+P+'%</td></tr>'});h+='<tr class="jas-total"><td colspan="3">Total</td><td>'+t+'</td><td>'+x+'</td><td></td></tr></tbody></table>';return h}
function render(dt){css();const d=parse(rows(dt)),rp=document.getElementById('reportPage');if(!rp)return;rp.querySelectorAll('.report-header,.status,.table-box,.report-actions').forEach(e=>e.style.display='none');let q=document.getElementById('jasMeetingModule');if(!q){q=document.createElement('div');q.id='jasMeetingModule';rp.appendChild(q)}const st=sectorTable(d.sector,d.sh,d.title),ft=facilityTable(d.facility,d.fh,d.title),overall=st.t?Math.round(st.x/st.t*100):0;q.innerHTML='<div class="jas-summary"><div class="jas-card"><b>'+d.sector.length+'</b><span>Total Sector</span></div><div class="jas-card"><b>'+st.f+'</b><span>Total AAM Facility</span></div><div class="jas-card"><b>'+st.t+'</b><span>Total Target</span></div><div class="jas-card"><b>'+st.x+'</b><span>Total Achievement</span></div><div class="jas-card"><b class="'+pc(overall)+'">'+overall+'%</b><span>Overall %</span></div></div>'+(d.sector.length?'<div class="jas-page">'+st.h+'</div>':'')+(d.facility.length?'<div class="jas-page">'+ft+'</div>':'')}
function load(){css();if(!window.google?.visualization?.Query)return;const q=new google.visualization.Query('https://docs.google.com/spreadsheets/d/'+SID+'/gviz/tq?gid='+GID+'&headers=0');q.setQuery('select A,B,C,D,E,F');q.send(r=>{if(!r.isError())render(r.getDataTable())})}
function install(){if(typeof openReport!=='function'||typeof REPORTS==='undefined'||openReport.__jasFixed)return;const old=openReport;function wrapped(i){const report=REPORTS[i];if(report&&report.name==='JAS Meeting'){document.getElementById('dashboardPage')?.classList.remove('active');document.getElementById('reportPage')?.classList.add('active');load();return}return old.apply(this,arguments)}wrapped.__jasFixed=true;window.openReport=wrapped}[0,100,300,700,1500,3000,5000].forEach(t=>setTimeout(install,t));
})();