/* JAS Meeting module — Sector Wise first, Facility Wise second */
(function(){
'use strict';
const GID='1018164338', SID=window.SPREADSHEET_ID;
const TITLE='Jan Arogya Samiti Meeting FY 2026-27 Till July 2026';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=v=>Number(String(v??'').replace(/,/g,'').replace('%','').trim())||0;
const isNIN=v=>/^\d{10}$/.test(String(v).replace(/\D/g,''));
function css(){if(document.getElementById('jas-fixed-css'))return;const s=document.createElement('style');s.id='jas-fixed-css';s.textContent=`#jasMeetingModule{display:block!important;width:100%}.jas-page{background:#fff;padding:10px;margin-bottom:14px;overflow:auto}.jas-table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:11px}.jas-table th,.jas-table td{border:1px solid #bbb;padding:6px 4px;text-align:center;vertical-align:middle;word-break:break-word}.jas-title{font-size:15px;font-weight:800}.jas-table th{font-weight:800}.jas-name{text-align:left}.jas-total{font-weight:800}@media(max-width:700px){.jas-table{font-size:9px}.jas-table th,.jas-table td{padding:4px 2px}}`;document.head.appendChild(s)}
function rows(dt){const facility=[],sector=[];for(let r=0;r<dt.getNumberOfRows();r++){let v=[];for(let c=0;c<6;c++)v.push(String(dt.getFormattedValue(r,c)||'').trim());if(!/^\d+$/.test(v[0]))continue;if(isNIN(v[1])&&v[2])facility.push({sn:v[0],nin:v[1],name:v[2],target:n(v[3]),ach:n(v[4]),pct:n(v[5])});else if(v[1]&&/^\d+$/.test(v[2]))sector.push({sn:v[0],sector:v[1],fac:n(v[2]),target:n(v[3]),ach:n(v[4]),pct:n(v[5])});}return{facility,sector}}
function pct(x){return '<td>'+n(x)+'%</td>'}
function sectorTable(a){let h='<table class="jas-table"><thead><tr><th colspan="6" class="jas-title">'+TITLE+'</th></tr><tr><th>SN</th><th>Sector</th><th>No of AAM Facility</th><th>Target<br>till May 26</th><th>Achievment</th><th>%</th></tr></thead><tbody>';a.forEach(r=>h+='<tr><td>'+esc(r.sn)+'</td><td class="jas-name">'+esc(r.sector)+'</td><td>'+r.fac+'</td><td>'+r.target+'</td><td>'+r.ach+'</td>'+pct(r.pct)+'</tr>');return h+'<tr class="jas-total"><td colspan="2">Total</td><td>'+a.reduce((s,r)=>s+r.fac,0)+'</td><td>'+a.reduce((s,r)=>s+r.target,0)+'</td><td>'+a.reduce((s,r)=>s+r.ach,0)+'</td><td></td></tr></tbody></table>'}
function facilityTable(a){let h='<table class="jas-table"><thead><tr><th colspan="6" class="jas-title">'+TITLE+'</th></tr><tr><th>SN</th><th>NIN</th><th>Name of Facility</th><th>Target<br>till July 26</th><th>Achievment</th><th>%</th></tr></thead><tbody>';a.forEach(r=>h+='<tr><td>'+esc(r.sn)+'</td><td>'+esc(r.nin)+'</td><td class="jas-name">'+esc(r.name)+'</td><td>'+r.target+'</td><td>'+r.ach+'</td>'+pct(r.pct)+'</tr>');return h+'<tr class="jas-total"><td colspan="3">Total</td><td>'+a.reduce((s,r)=>s+r.target,0)+'</td><td>'+a.reduce((s,r)=>s+r.ach,0)+'</td><td></td></tr></tbody></table>'}
function render(dt){css();const d=rows(dt),rp=document.getElementById('reportPage');if(!rp)return;rp.querySelectorAll('.report-header,.status,.table-box,.report-actions').forEach(e=>e.style.display='none');let q=document.getElementById('jasMeetingModule');if(!q){q=document.createElement('div');q.id='jasMeetingModule';rp.appendChild(q)}q.innerHTML=(d.sector.length?'<div class="jas-page">'+sectorTable(d.sector)+'</div>':'')+(d.facility.length?'<div class="jas-page">'+facilityTable(d.facility)+'</div>':'')||'<div class="jas-page">JAS Meeting data नहीं मिला।</div>'}
function direct(){css();if(!window.google?.visualization?.Query||!SID)return;const q=new google.visualization.Query('https://docs.google.com/spreadsheets/d/'+SID+'/gviz/tq?gid='+GID+'&headers=0');q.setQuery('select A,B,C,D,E,F');q.send(r=>{if(!r.isError())render(r.getDataTable())})}
function install(){if(!window.openReport||!window.REPORTS)return;if(!window.openReport.__jasFixed){const old=window.openReport;const fn=function(i){if(window.REPORTS[i]?.name==='JAS Meeting'){document.getElementById('dashboardPage')?.classList.remove('active');document.getElementById('reportPage')?.classList.add('active');document.getElementById('reportTitle').innerText='🤝 JAS Meeting';document.getElementById('reportDescription').innerText='Jan Arogya Samiti Meeting Reporting';document.querySelectorAll('#menuButtons .menu-btn').forEach((b,k)=>b.classList.toggle('active',k===i));document.getElementById('dashboardBtn')?.classList.remove('active');direct();return}return old.apply(this,arguments)};fn.__jasFixed=true;window.openReport=fn}}
window.renderJASMeeting=direct;[0,200,500,1000,2000,4000].forEach(t=>setTimeout(install,t));
})();