/* NCD MODULE — 3 reports + correct Total rows + summary + wrapped columns + borders */
(function(){
'use strict';
const SHEET_ID='1XAGjeCrLSVzTIraRSGkkjejXlrJEn-G2GxUEnN6ZCI0',NCD_GID='1254412412',LAST_UPDATED='17-Aug-2026 23:06:53';
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function rows(data){const o=[];for(let r=0;r<data.getNumberOfRows();r++){const a=[];for(let c=0;c<data.getNumberOfColumns();c++){let v='';try{v=data.getFormattedValue(r,c)||data.getValue(r,c)||''}catch(e){}a.push(clean(v))}o.push(a)}return o}
const title=r=>/NCD\s*status\s*2026-27/i.test(r.join(' '));
const total=r=>/^(total|योग|कुल)$/i.test(clean(r[0]));
const header=r=>/subcenter|sector|total\s+population|screening\s+target|enrollment\s*30|abha\s*link/i.test(r.join(' ').toLowerCase());
function css(){if(document.getElementById('ncd3css'))document.getElementById('ncd3css').remove();const s=document.createElement('style');s.id='ncd3css';s.textContent=`#ncdModuleContainer{width:100%;box-sizing:border-box}.ncd-summary-title{text-align:center;background:#075985;color:#fff;border-radius:8px;padding:9px;margin:0 0 10px;font-weight:900;font-size:17px}.ncd-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:9px;margin-bottom:16px}.ncd-card{background:#fff;border:1px solid #94a3b8;border-radius:9px;padding:10px;text-align:center;box-shadow:0 2px 8px rgba(0,0,0,.06)}.ncd-card b{display:block;color:#075985;font-size:12px}.ncd-card strong{font-size:20px;display:block;margin-top:4px}.ncd-menu{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.ncd-menu button{padding:10px 15px;border:1px solid #075985;border-radius:7px;background:#fff;color:#075985;font-weight:800;cursor:pointer}.ncd-menu button.active{background:#075985;color:#fff}.ncd-report{display:none}.ncd-report.active{display:block}.ncd-final-box{background:#fff;border:1px solid #94a3b8;border-radius:10px;padding:10px;margin-bottom:18px;box-shadow:0 3px 12px rgba(0,0,0,.07);overflow:auto}.ncd-final-title{text-align:center;background:#e0f2fe;color:#075985;border:1px solid #93c5fd;border-left:5px solid #075985;padding:9px;margin-bottom:9px;font-weight:900}.ncd-final-table{width:100%;border-collapse:collapse;border:2px solid #475569;font-size:12px;min-width:1000px;table-layout:fixed}.ncd-final-table th{background:#075985;color:#fff;border:1px solid #cbd5e1;padding:8px 6px;text-align:center;vertical-align:middle;white-space:normal;overflow-wrap:anywhere;word-break:normal;line-height:1.25}.ncd-final-table td{border:1px solid #94a3b8;padding:7px 6px;text-align:center;vertical-align:middle;white-space:normal;overflow-wrap:anywhere}.ncd-final-table th:nth-child(2),.ncd-final-table td:nth-child(2){width:105px;white-space:normal;overflow-wrap:anywhere}.ncd-final-table td:first-child{text-align:left;font-weight:700;min-width:120px}.ncd-final-table .ncd-total-row{background:#dbeafe!important;font-weight:900}.ncd-pct-good{background:#dcfce7!important;color:#166534!important;font-weight:900}.ncd-pct-mid{background:#fef9c3!important;color:#854d0e!important;font-weight:900}.ncd-pct-low{background:#fee2e2!important;color:#991b1b!important;font-weight:900}`;document.head.appendChild(s)}
function pctClass(v){const n=parseFloat(String(v).replace('%',''));if(isNaN(n))return '';return n>=80?'ncd-pct-good':n>=50?'ncd-pct-mid':'ncd-pct-low'}
function makeTable(data,part,totalRow){const t=document.createElement('table');t.className='ncd-final-table';const h=part==='enroll'?['Subcenter','Total Population','Screening Target (47.8% of Total Population)','Enrollment 30+ (Progressive)','%','ABHA Link (Progressive)','ABHA Link %']:part==='htn'?['Subcenter','Screening','%','Estimated Hypertensive Patient (NFHS - 29%)','Under Treatment','%','Followup','%','Under Control','%']:['Subcenter','Screening','%','Estimated Diabetes Patients (NFHS - 10.8%)','Under Treatment','%','Followup','%','Under Control','%'];const thead=document.createElement('thead'),hr=document.createElement('tr');h.forEach(x=>{const th=document.createElement('th');th.textContent=x;hr.appendChild(th)});thead.appendChild(hr);t.appendChild(thead);const tb=document.createElement('tbody');const source=data.slice();if(totalRow)source.push(totalRow);source.forEach(r=>{if(!r||!r.some(Boolean))return;let vals=part==='enroll'?r.slice(0,7):part==='htn'?[r[0],r[7],r[8],r[9],r[10],r[11],r[12],r[13],r[14],r[15]]:[r[0],r[16],r[17],r[18],r[19],r[20],r[21],r[22],r[23],r[24]];const tr=document.createElement('tr');const isTot=total(r);if(isTot)tr.className='ncd-total-row';vals.forEach((v,i)=>{const td=document.createElement('td');td.textContent=v||'';if(h[i]==='%'&&!isTot){const c=pctClass(v);if(c)td.className=c}tr.appendChild(td)});tb.appendChild(tr)});t.appendChild(tb);return t}
function report(name,data,part,totalRow){const b=document.createElement('div');b.className='ncd-report';b.dataset.part=part;const h=document.createElement('div');h.className='ncd-final-title';h.textContent=name;b.appendChild(h);b.appendChild(makeTable(data,part,totalRow));return b}
function card(label,val){const d=document.createElement('div');d.className='ncd-card';d.innerHTML='<b>'+label+'</b><strong>'+((val==null||val==='')?'-':val)+'</strong>';return d}
function summary(r){const s=document.createElement('div');s.className='ncd-summary';[['Total Population',r[1]],['Screening Target',r[2]],['Enrollment 30+',r[3]],['Enrollment %',r[4]],['ABHA Link',r[5]],['ABHA Link %',r[6]],['HTN Screening',r[7]],['HTN Screening %',r[8]],['HTN Estimated',r[9]],['HTN Treatment',r[10]],['HTN Treatment %',r[11]],['HTN Followup',r[12]],['HTN Followup %',r[13]],['HTN Control',r[14]],['HTN Control %',r[15]],['DM Screening',r[16]],['DM Screening %',r[17]],['DM Estimated',r[18]],['DM Treatment',r[19]],['DM Treatment %',r[20]],['DM Followup',r[21]],['DM Followup %',r[22]],['DM Control',r[23]],['DM Control %',r[24]]].forEach(x=>s.appendChild(card(x[0],x[1])));return s}
function section(rs,start,end){const head=rs.slice(start,end),ti=head.findIndex(total);return ti>=0?{data:head.slice(0,ti),total:head[ti]}:{data:head,total:null}}
function draw(data){css();const old=document.getElementById('ncdModuleContainer');if(old)old.remove();const out=document.createElement('div');out.id='ncdModuleContainer';(document.getElementById('pdfArea')||document.body).appendChild(out);const rs=rows(data);let ti=[];rs.forEach((r,i)=>{if(title(r))ti.push(i)});const a=ti[0]??-1,b=ti[1]??-1;let fh=-1,sh=-1;for(let i=a+1;i<(b<0?rs.length:b);i++)if(header(rs[i])){fh=i;break}for(let i=b+1;i<rs.length;i++)if(header(rs[i])){sh=i;break}const sec=fh>=0?section(rs,fh+1,b<0?rs.length:b):{data:[],total:null},fac=sh>=0?section(rs,sh+1,rs.length):{data:[],total:null},summaryRow=sec.total||fac.total;const hd=document.createElement('div');hd.className='ncd-final-title';hd.textContent='NCD Status 2026-27 As On Last Updated On : '+LAST_UPDATED;out.appendChild(hd);const st=document.createElement('div');st.className='ncd-summary-title';st.textContent='NCD Summary Report';out.appendChild(st);if(summaryRow)out.appendChild(summary(summaryRow));const menu=document.createElement('div');menu.className='ncd-menu';[['Enrollment & ABHA Link','enroll'],['HTN','htn'],['DM','dm']].forEach((x,i)=>{const btn=document.createElement('button');btn.textContent=x[0];if(i===0)btn.className='active';btn.onclick=()=>{menu.querySelectorAll('button').forEach(q=>q.classList.remove('active'));btn.classList.add('active');out.querySelectorAll('.ncd-report').forEach(q=>q.classList.toggle('active',q.dataset.part===x[1]))};menu.appendChild(btn)});out.appendChild(menu);[['Sector Wise',sec],['Facility Wise',fac]].forEach(x=>{const box=document.createElement('div');box.className='ncd-final-box';const h=document.createElement('div');h.className='ncd-final-title';h.textContent=x[0];box.appendChild(h);['enroll','htn','dm'].forEach((p,i)=>{const r=report(['Enrollment & ABHA Link','HTN','DM'][i],x[1].data,p,x[1].total);if(i===0)r.classList.add('active');box.appendChild(r)});out.appendChild(box)})}
function renderNCDTable(){if(window.google&&google.visualization){const q=new google.visualization.Query('https://docs.google.com/spreadsheets/d/'+SHEET_ID+'/gviz/tq?gid='+NCD_GID+'&headers=0');q.setQuery('select *');q.send(r=>{if(!r.isError())draw(r.getDataTable())})}}window.renderNCDTable=renderNCDTable;
})();