/* NCD MODULE — 3 reports + summary cards + total rows + % performance colors */
(function(){
'use strict';
const SHEET_ID='1XAGjeCrLSVzTIraRSGkkjejXlrJEn-G2GxUEnN6ZCI0',NCD_GID='1254412412',LAST_UPDATED='17-Aug-2026 23:06:53';
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function rows(data){const o=[];for(let r=0;r<data.getNumberOfRows();r++){const a=[];for(let c=0;c<data.getNumberOfColumns();c++){let v='';try{v=data.getFormattedValue(r,c)||data.getValue(r,c)||''}catch(e){}a.push(clean(v))}o.push(a)}return o}
const title=r=>/NCD\s*status\s*2026-27/i.test(r.join(' ')), total=r=>/^(total|योग|कुल)$/i.test(clean(r[0])), header=r=>/subcenter|sector|total\s+population|screening\s+target|enrollment\s*30|abha\s*link/i.test(r.join(' ').toLowerCase());
function css(){if(document.getElementById('ncd3css'))return;const s=document.createElement('style');s.id='ncd3css';s.textContent=`#ncdModuleContainer{width:100%;box-sizing:border-box}.ncd-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:9px;margin-bottom:14px}.ncd-card{background:#fff;border:1px solid #cbd5e1;border-radius:9px;padding:10px;text-align:center;box-shadow:0 2px 8px rgba(0,0,0,.06)}.ncd-card b{display:block;color:#075985;font-size:12px}.ncd-card strong{font-size:20px;display:block;margin-top:4px}.ncd-menu{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.ncd-menu button{padding:10px 15px;border:1px solid #075985;border-radius:7px;background:#fff;color:#075985;font-weight:800;cursor:pointer}.ncd-menu button.active{background:#075985;color:#fff}.ncd-report{display:none}.ncd-report.active{display:block}.ncd-final-box{background:#fff;border-radius:10px;padding:10px;margin-bottom:18px;box-shadow:0 3px 12px rgba(0,0,0,.07);overflow:auto}.ncd-final-title{text-align:center;background:#e0f2fe;color:#075985;border-left:5px solid #075985;padding:9px;margin-bottom:9px;font-weight:900}.ncd-final-table{width:100%;border-collapse:collapse;font-size:12px;min-width:900px}.ncd-final-table th{background:#075985;color:#fff;border:1px solid #cbd5e1;padding:8px;text-align:center;vertical-align:middle}.ncd-final-table td{border:1px solid #cbd5e1;padding:7px;text-align:center}.ncd-final-table td:first-child{text-align:left;font-weight:700}.ncd-final-table .ncd-total-row{background:#dbeafe!important;font-weight:900}.ncd-pct-good{background:#dcfce7!important;color:#166534!important;font-weight:900}.ncd-pct-mid{background:#fef9c3!important;color:#854d0e!important;font-weight:900}.ncd-pct-low{background:#fee2e2!important;color:#991b1b!important;font-weight:900}`;document.head.appendChild(s)}
function pctClass(v){const n=parseFloat(String(v).replace('%',''));if(isNaN(n))return '';return n>=80?'ncd-pct-good':n>=50?'ncd-pct-mid':'ncd-pct-low'}
function makeTable(data,part){const t=document.createElement('table');t.className='ncd-final-table';const h=part==='enroll'?['Subcenter','Total Population','Screening Target (47.8% of Total Population)','Enrollment 30+ (Progressive)','%','ABHA Link (Progressive)','ABHA Link %']:part==='htn'?['Subcenter','Screening','%','Estimated Hypertensive Patient (NFHS - 29%)','Under Treatment','%','Followup','%','Under Control','%']:['Subcenter','Screening','%','Estimated Diabetes Patients (NFHS - 10.8%)','Under Treatment','%','Followup','%','Under Control','%'];const thead=document.createElement('thead'),hr=document.createElement('tr');h.forEach(x=>{const th=document.createElement('th');th.textContent=x;hr.appendChild(th)});thead.appendChild(hr);t.appendChild(thead);const tb=document.createElement('tbody');data.forEach(r=>{if(!r.some(Boolean))return;let vals=part==='enroll'?r.slice(0,7):part==='htn'?[r[0],r[7],r[8],r[9],r[10],r[11],r[12],r[13],r[14],r[15]]:[r[0],r[16],r[17],r[18],r[19],r[20],r[21],r[22],r[23],r[24]];const tr=document.createElement('tr');if(total(r))tr.className='ncd-total-row';vals.forEach((v,i)=>{const td=document.createElement('td');td.textContent=v||'';if(h[i]==='%'&& !total(r)){const c=pctClass(v);if(c)td.className=c}tr.appendChild(td)});tb.appendChild(tr)});t.appendChild(tb);return t}
function report(name,data,part){const b=document.createElement('div');b.className='ncd-report';b.dataset.part=part;const h=document.createElement('div');h.className='ncd-final-title';h.textContent=name;b.appendChild(h);b.appendChild(makeTable(data,part));return b}
function card(label,val){const d=document.createElement('div');d.className='ncd-card';d.innerHTML='<b>'+label+'</b><strong>'+((val==null||val==='')?'-':val)+'</strong>';return d}
function summary(data){const s=document.createElement('div');s.className='ncd-summary';const last=data[data.length-1]||[];const idx=v=>last.indexOf(v);[['Population',last[1]],['Screening Target',last[2]],['Enrollment 30+',last[3]],['Enrollment %',last[4]],['ABHA Link',last[5]],['ABHA %',last[6]],['HTN Screening',last[7]],['HTN Treatment',last[10]],['HTN Followup',last[12]],['HTN Control',last[14]],['DM Screening',last[16]],['DM Treatment',last[19]],['DM Followup',last[21]],['DM Control',last[23]]].forEach(x=>s.appendChild(card(x[0],x[1])));return s}
function draw(data){css();const old=document.getElementById('ncdModuleContainer');if(old)old.remove();const out=document.createElement('div');out.id='ncdModuleContainer';(document.getElementById('pdfArea')||document.body).appendChild(out);const rs=rows(data);let ti=[];rs.forEach((r,i)=>{if(title(r))ti.push(i)});const a=ti[0]??-1,b=ti[1]??-1;let fh=-1,sh=-1;for(let i=a+1;i<(b<0?rs.length:b);i++)if(header(rs[i])){fh=i;break}for(let i=b+1;i<rs.length;i++)if(header(rs[i])){sh=i;break}const end=(x,y)=>{for(let i=x;i<y;i++)if(total(rs[i]))return i;return y};const fr=fh>=0?rs.slice(fh+1,end(fh+1,b<0?rs.length:b)):[],sr=sh>=0?rs.slice(sh+1,end(sh+1,rs.length)):[];const hd=document.createElement('div');hd.className='ncd-final-title';hd.textContent='NCD Status 2026-27 As On Last Updated On : '+LAST_UPDATED;out.appendChild(hd);out.appendChild(summary(sr.length?sr:fr));const menu=document.createElement('div');menu.className='ncd-menu';[['Enrollment & ABHA Link','enroll'],['HTN','htn'],['DM','dm']].forEach((x,i)=>{const btn=document.createElement('button');btn.textContent=x[0];if(i===0)btn.className='active';btn.onclick=()=>{menu.querySelectorAll('button').forEach(q=>q.classList.remove('active'));btn.classList.add('active');out.querySelectorAll('.ncd-report').forEach(q=>q.classList.toggle('active',q.dataset.part===x[1]))};menu.appendChild(btn)});out.appendChild(menu);[['Sector Wise',sr],['Facility Wise',fr]].forEach(x=>{const box=document.createElement('div');box.className='ncd-final-box';const h=document.createElement('div');h.className='ncd-final-title';h.textContent=x[0];box.appendChild(h);['enroll','htn','dm'].forEach((p,i)=>{const r=report(['Enrollment & ABHA Link','HTN','DM'][i],x[1],p);if(i===0)r.classList.add('active');box.appendChild(r)});out.appendChild(box)})}
function renderNCDTable(){if(window.google&&google.visualization){const q=new google.visualization.Query('https://docs.google.com/spreadsheets/d/'+SHEET_ID+'/gviz/tq?gid='+NCD_GID+'&headers=0');q.setQuery('select *');q.send(r=>{if(!r.isError())draw(r.getDataTable())})}}window.renderNCDTable=renderNCDTable;
})();