// Kharsia Health Dashboard main controller

const SPREADSHEET_ID = "1XAGjeCrLSVzTIraRSGkkjejXlrJEn-G2GxUEnN6ZCI0";
const REPORTS=[
{name:"Ayushman Card",icon:"💳",gid:"925649620",description:"आयुष्मान कार्ड एवं वय वंदन कार्ड की प्रगति"},
{name:"RCH 2.0",icon:"👩‍🍼",gid:"1044088930",description:"RCH 2.0 PW Registration Detail"},
{name:"NCD",icon:"❤️",gid:"1254412412",description:"NCD Status 2026-27"},
{name:"JAS Meeting",icon:"🤝",gid:"1018164338",description:"JAS Meeting Reporting"},
{name:"Health & Wellness Center",icon:"🏥",gid:"0",description:"Health Wellness Center - Block Kharsia"},
{name:"Ayushman Shivir",icon:"🏕️",gid:"1262815420",description:"Ayushman Shivir Reporting FY 2026-27"},
{name:"Wellness Activity",icon:"🩺",gid:"447031017",description:"Ayushman Arogya Mandir Wellness Activity"},
{name:"RBSK",icon:"👶",gid:"1502752823",description:"राष्ट्रीय बाल स्वास्थ्य कार्यक्रम"},
{name:"NRC Kharsia",icon:"🏥",gid:"1010102020",description:"NRC Kharsia Reporting"},
{name:"Blindness Control",icon:"👁️",gid:"1002009767",description:"National Blindness Control Programme"},
{name:"NQAS Certification",icon:"🏅",gid:"728123647",description:"NQAS Certification Detail Kharsia"},
{name:"Dialysis",icon:"💧",gid:"781496964",description:"प्रधानमंत्री राष्ट्रीय डायलिसिस कार्यक्रम"},
{name:"NLEP",icon:"🦠",gid:"1536656599",description:"National Leprosy Eradication Programme"}
];
let currentReportIndex=null,currentData=null;
const RCH_SECTORS=["Barra","Binjkot","Gorpar","Jobi","Sarwani","Sondka","Turekela","Urban Kharsia"];
function showDashboard(){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('dashboardPage')?.classList.add('active');document.querySelectorAll('.menu-btn').forEach(b=>b.classList.remove('active'));document.getElementById('dashboardBtn')?.classList.add('active');currentReportIndex=null;loadBlockSummary();}
function createMenu(){const box=document.getElementById('menuButtons');if(!box)return;box.innerHTML='';REPORTS.forEach((r,i)=>{const b=document.createElement('button');b.className='menu-btn';b.innerHTML=`${r.icon} ${r.name}`;b.onclick=()=>openReport(i);box.appendChild(b)});const cards=document.getElementById('dashboardCards');if(cards)cards.innerHTML=REPORTS.map((r,i)=>`<div class="card" onclick="openReport(${i})"><div class="card-icon">${r.icon}</div><h3>${r.name}</h3><p>${r.description}</p></div>`).join('');loadBlockSummary();}
function gvizUrl(gid,format='json'){return `https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/gviz/tq?tqx=out:${format==='csv'?'csv':'json'}&gid=${encodeURIComponent(gid)}`;}
async function fetchWithTimeout(url,ms=15000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r}catch(e){if(e.name==='AbortError')throw new Error('Request timed out');throw e}finally{clearTimeout(t)}}
function parseCsvLine(line){const a=[];let v='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(ch===','&&!q){a.push(v);v=''}else v+=ch}a.push(v);return a}
function parseCsv(text){const lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return{cols:[],rows:[]};const m=lines.map(parseCsvLine),cols=m[0].map((v,i)=>String(v||'').trim()||`Column ${i+1}`);return{cols,rows:m.slice(1).map(r=>cols.map((_,i)=>r[i]??''))}}
async function fetchSheetRows(report){if(!report?.gid||report.gid==='0')throw new Error('Google Sheet GID उपलब्ध नहीं है');let e1='';try{const r=await fetchWithTimeout(gvizUrl(report.gid));const t=await r.text(),s=t.indexOf('{'),e=t.lastIndexOf('}');if(s<0||e<s)throw new Error('Invalid JSON');const j=JSON.parse(t.slice(s,e+1)),tb=j.table||{},cols=(tb.cols||[]).map((c,i)=>c.label||`Column ${i+1}`),rows=(tb.rows||[]).map(x=>(x.c||[]).map(c=>c?(c.v??c.f??''):''));if(!cols.length)throw new Error('No columns');return{cols,rows}}catch(x){e1=x.message||'GViz failed'}try{const r=await fetchWithTimeout(gvizUrl(report.gid,'csv')),d=parseCsv(await r.text());if(!d.cols.length)throw new Error('No CSV data');return d}catch(x){throw new Error(`${e1}; fallback: ${x.message||'CSV failed'}`)}}
function num(v){const s=String(v??'').replace(/,/g,'').replace(/%/g,'').trim();if(!s)return null;const n=Number(s);return Number.isFinite(n)?n:null}function fmt(n){return Number.isInteger(n)?n.toLocaleString('en-IN'):n.toLocaleString('en-IN',{maximumFractionDigits:2})}
function buildModuleSummary(data){const rows=data.rows.filter(r=>r.some(v=>String(v??'').trim()));const metrics=[];data.cols.forEach((label,c)=>{let total=0,count=0;rows.forEach(r=>{const n=num(r[c]);if(n!==null){total+=n;count++}});if(count&&label&&!/%|percent|rate|क्रम|serial/i.test(label))metrics.push({label,total})});metrics.sort((a,b)=>b.total-a.total);return{rows:rows.length,metrics:metrics.slice(0,3)}}
async function loadBlockSummary(){const grid=document.getElementById('blockSummaryGrid'),status=document.getElementById('blockSummaryStatus');if(!grid||!status)return;status.textContent='सभी programme का live summary load हो रहा है...';grid.innerHTML='';const results=await Promise.all(REPORTS.map(async r=>{try{return{r,data:await fetchSheetRows(r)}}catch(e){return{r,error:e.message}}}));let ok=0;results.forEach(({r,data,error})=>{const c=document.createElement('div');c.className='summary-module-card'+(error?' summary-error':'');c.onclick=()=>openReport(REPORTS.indexOf(r));if(error){c.innerHTML=`<div class="summary-module-title"><span class="summary-module-icon">${r.icon}</span>${r.name}</div><div style="font-size:12px">❌ ${error}</div>`}else{ok++;const s=buildModuleSummary(data);c.innerHTML=`<div class="summary-module-title"><span class="summary-module-icon">${r.icon}</span>${r.name}</div><div class="summary-stats"><div class="summary-stat"><div class="summary-stat-label">Data Rows</div><div class="summary-stat-value">${fmt(s.rows)}</div></div><div class="summary-stat"><div class="summary-stat-label">Status</div><div class="summary-stat-value">Live</div></div></div>${s.metrics.map(m=>`<div class="summary-metric"><span class="summary-metric-name">${m.label}</span><span class="summary-metric-value">${fmt(m.total)}</span></div>`).join('')}`}grid.appendChild(c)});status.textContent=`Block Kharsia Summary: ${ok}/${REPORTS.length} programmes का live data load हुआ।`}
function clearTable(){const t=document.getElementById('reportTable');if(t){t.querySelector('thead').innerHTML='';t.querySelector('tbody').innerHTML=''}}
function renderNormalTable(data){const t=document.getElementById('reportTable');if(!t)return;const th=t.querySelector('thead'),tb=t.querySelector('tbody');th.innerHTML=`<tr>${Array.from({length:data.getNumberOfColumns()},(_,c)=>`<th>${escapeHtml(data.getColumnLabel(c))}</th>`).join('')}</tr>`;for(let r=0;r<data.getNumberOfRows();r++){const tr=document.createElement('tr');for(let c=0;c<data.getNumberOfColumns();c++){const td=document.createElement('td');td.textContent=data.getFormattedValue(r,c);tr.appendChild(td)}tb.appendChild(tr)}}
function escapeHtml(s){const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML}
function filterTable(){const q=(document.getElementById('searchBox')?.value||'').toLowerCase();document.querySelectorAll('#reportTable tbody tr').forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(q)?'':'none')}
function downloadExcel(){const t=document.getElementById('reportTable');if(window.XLSX&&t){const wb=XLSX.utils.table_to_book(t,{sheet:'Report'});XLSX.writeFile(wb,`${REPORTS[currentReportIndex]?.name||'Report'}.xlsx`)}}
function downloadPDF(){const area=document.getElementById('pdfArea');if(window.html2pdf&&area)html2pdf().from(area).set({margin:5,filename:`${REPORTS[currentReportIndex]?.name||'Report'}.pdf`,html2canvas:{scale:1},jsPDF:{orientation:'landscape',unit:'mm',format:'a4'}}).save()}
function printReport(){window.print()}
async function openReport(index){currentReportIndex=index;const report=REPORTS[index];document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('reportPage')?.classList.add('active');document.querySelectorAll('.menu-btn').forEach(b=>b.classList.remove('active'));[...document.querySelectorAll('.menu-btn')].find(b=>b.textContent.includes(report.name))?.classList.add('active');document.getElementById('reportTitle').textContent=report.name;document.getElementById('reportDescription').textContent=report.description;const status=document.getElementById('status');status.className='status';status.textContent='Google Sheet से data load हो रहा है...';try{const data=await fetchSheetRows(report);currentData=data;clearTable();renderNormalTable({getNumberOfColumns:()=>data.cols.length,getNumberOfRows:()=>data.rows.length,getColumnLabel:c=>data.cols[c],getFormattedValue:(r,c)=>String(data.rows[r]?.[c]??'')});status.className='status success';status.textContent='✓ Google Sheet से data successfully loaded'}catch(e){status.className='status error';status.textContent='❌ Google Sheet से data load नहीं हुआ: '+(e.message||e)}}
function refreshReport(){if(currentReportIndex!==null)openReport(currentReportIndex)}
window.addEventListener('DOMContentLoaded',createMenu);