// Kharsia Health Dashboard — dashboard controller
const SPREADSHEET_ID="1XAGjeCrLSVzTIraRSGkkjejXlrJEn-G2GxUEnN6ZCI0";
const REPORTS=[
{name:"Ayushman Card",icon:"💳",gid:"925649620",description:"आयुष्मान कार्ड एवं वय वंदन कार्ड की प्रगति",url:"ayushman.html"},
{name:"RCH 2.0",icon:"👩‍🍼",gid:"1044088930",description:"RCH 2.0 PW Registration Detail",url:"rch.html"},
{name:"NCD",icon:"❤️",gid:"1254412412",description:"NCD Status 2026-27",url:"ncd.html"},
{name:"JAS Meeting",icon:"🤝",gid:"1018164338",description:"JAS Meeting Reporting"},
{name:"Health & Wellness Center",icon:"🏥",gid:"0",description:"Health Wellness Center - Block Kharsia"},
{name:"Ayushman Shivir",icon:"🏕️",gid:"1262815420",description:"Ayushman Shivir Reporting FY 2026-27"},
{name:"Wellness Activity",icon:"🩺",gid:"447031017",description:"Ayushman Arogya Mandir Wellness Activity"},
{name:"RBSK",icon:"👶",gid:"1502752823",description:"राष्ट्रीय बाल स्वास्थ्य कार्यक्रम"},
{name:"NRC Kharsia",icon:"🏥",gid:"1010102020",description:"NRC Kharsia Reporting"},
{name:"Blindness Control",icon:"👁️",gid:"1002009767",description:"National Blindness Control Programme"},
{name:"NQAS Certification",icon:"🏅",gid:"728123647",description:"NQAS Certification Detail Kharsia"},
{name:"Dialysis",icon:"💧",gid:"781496964",description:"प्रधानमंत्री राष्ट्रीय डायलिसिस कार्यक्रम"},
{name:"NLEP",icon:"🦠",gid:"1536656599",description:"National Leprosy Eradication Programme"}
];
function gvizUrl(gid,format="json"){return `https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/gviz/tq?tqx=out:${format==='csv'?'csv':'json'}&gid=${encodeURIComponent(gid)}`}
async function fetchSheetRows(report){if(!report?.gid||report.gid==='0')throw new Error('Google Sheet GID उपलब्ध नहीं है');const r=await fetch(gvizUrl(report.gid),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const t=await r.text(),s=t.indexOf('{'),e=t.lastIndexOf('}');if(s<0||e<s)throw new Error('Invalid Sheet data');const j=JSON.parse(t.slice(s,e+1)),tb=j.table||{};const cols=(tb.cols||[]).map((c,i)=>c.label||`Column ${i+1}`);const rows=(tb.rows||[]).map(x=>(x.c||[]).map(c=>c?(c.v??c.f??''):''));return{cols,rows}}
function num(v){const s=String(v??'').replace(/,/g,'').replace(/%/g,'').trim();if(!s)return null;const n=Number(s);return Number.isFinite(n)?n:null}
function fmt(n){return Number.isInteger(n)?n.toLocaleString('en-IN'):n.toLocaleString('en-IN',{maximumFractionDigits:2})}
function buildModuleSummary(data){const rows=data.rows.filter(r=>r.some(v=>String(v??'').trim()));const metrics=[];data.cols.forEach((label,c)=>{let total=0,count=0;rows.forEach(r=>{const n=num(r[c]);if(n!==null){total+=n;count++}});if(count&&label&&!/%|percent|rate|क्रम|serial|sn/i.test(label))metrics.push({label,total})});metrics.sort((a,b)=>b.total-a.total);return{rows:rows.length,metrics:metrics.slice(0,3)}}
function makeCards(){const box=document.getElementById('dashboardCards');if(!box)return;box.innerHTML=REPORTS.map(r=>`<a class="card" href="${r.url||'#'}" ${r.url?'':'onclick="openByName(\''+r.name+'\');return false;"'}><div class="card-icon">${r.icon}</div><div><h3>${r.name}</h3><p>${r.description}</p></div><span class="card-arrow">›</span></a>`).join('')}
function openByName(name){const r=REPORTS.find(x=>x.name===name);if(!r)return;if(r.url){location.href=r.url;return}window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});alert(r.gid==='0'?`${r.name}: Google Sheet GID उपलब्ध नहीं है।`:`${r.name} का dedicated page अगला चरण है।`)}
async function loadBlockSummary(){const grid=document.getElementById('blockSummaryGrid'),status=document.getElementById('blockSummaryStatus');if(!grid||!status)return;status.textContent='सभी programme का live summary load हो रहा है...';grid.innerHTML='';let ok=0;const results=await Promise.all(REPORTS.map(async r=>{try{return{r,data:await fetchSheetRows(r)}}catch(error){return{r,error}}}));results.forEach(({r,data,error})=>{const c=document.createElement('div');c.className='summary-module-card'+(error?' summary-error':'');if(r.url)c.onclick=()=>location.href=r.url;else c.onclick=()=>openByName(r.name);if(error){c.innerHTML=`<div class="summary-module-title"><span class="summary-module-icon">${r.icon}</span><span>${r.name}</span></div><div class="summary-error-text">❌ ${error.message}</div>`}else{ok++;const s=buildModuleSummary(data);c.innerHTML=`<div class="summary-module-title"><span class="summary-module-icon">${r.icon}</span><span>${r.name}</span></div><div class="summary-stats"><div class="summary-stat"><div class="summary-stat-label">Data Rows</div><div class="summary-stat-value">${fmt(s.rows)}</div></div><div class="summary-stat"><div class="summary-stat-label">Status</div><div class="summary-stat-value live">Live</div></div></div>${s.metrics.map(m=>`<div class="summary-metric"><span class="summary-metric-name">${m.label}</span><span class="summary-metric-value">${fmt(m.total)}</span></div>`).join('')}`}grid.appendChild(c)});status.textContent=`Block Kharsia Summary: ${ok}/${REPORTS.length} programmes का live data load हुआ।`}
window.addEventListener('DOMContentLoaded',()=>{makeCards();loadBlockSummary()});